<?php

declare(strict_types=1);

namespace SvkDigital\Currency\Enums;

use SvkDigital\Currency\ValueObjects\CurrencyCode;

/**
 * ISO-4217 reference
 */
enum CurrencyEnum: string
{
    case AED = 'AED';
    case AFN = 'AFN';
    case ALL = 'ALL';
    case AMD = 'AMD';
    case ANG = 'ANG';
    case AOA = 'AOA';
    case ARS = 'ARS';
    case AUD = 'AUD';
    case AWG = 'AWG';
    case AZN = 'AZN';
    case BAM = 'BAM';
    case BBD = 'BBD';
    case BDT = 'BDT';
    case BGN = 'BGN';
    case BHD = 'BHD';
    case BIF = 'BIF';
    case BMD = 'BMD';
    case BND = 'BND';
    case BOB = 'BOB';
    case BOV = 'BOV';
    case BRL = 'BRL';
    case BSD = 'BSD';
    case BTN = 'BTN';
    case BWP = 'BWP';
    case BYR = 'BYR';
    case BZD = 'BZD';
    case CAD = 'CAD';
    case CDF = 'CDF';
    case CHE = 'CHE';
    case CHF = 'CHF';
    case CHW = 'CHW';
    case CLF = 'CLF';
    case CLP = 'CLP';
    case CNY = 'CNY';
    case COP = 'COP';
    case COU = 'COU';
    case CRC = 'CRC';
    case CUC = 'CUC';
    case CUP = 'CUP';
    case CVE = 'CVE';
    case CZK = 'CZK';
    case DJF = 'DJF';
    case DKK = 'DKK';
    case DOP = 'DOP';
    case DZD = 'DZD';
    case EGP = 'EGP';
    case ERN = 'ERN';
    case ETB = 'ETB';
    case EUR = 'EUR';
    case FJD = 'FJD';
    case FKP = 'FKP';
    case GBP = 'GBP';
    case GEL = 'GEL';
    case GHS = 'GHS';
    case GIP = 'GIP';
    case GMD = 'GMD';
    case GNF = 'GNF';
    case GTQ = 'GTQ';
    case GYD = 'GYD';
    case HKD = 'HKD';
    case HNL = 'HNL';
    case HRK = 'HRK';
    case HTG = 'HTG';
    case HUF = 'HUF';
    case IDR = 'IDR';
    case ILS = 'ILS';
    case INR = 'INR';
    case IQD = 'IQD';
    case IRR = 'IRR';
    case ISK = 'ISK';
    case JMD = 'JMD';
    case JOD = 'JOD';
    case JPY = 'JPY';
    case KES = 'KES';
    case KGS = 'KGS';
    case KHR = 'KHR';
    case KMF = 'KMF';
    case KPW = 'KPW';
    case KRW = 'KRW';
    case KWD = 'KWD';
    case KYD = 'KYD';
    case KZT = 'KZT';
    case LAK = 'LAK';
    case LBP = 'LBP';
    case LKR = 'LKR';
    case LRD = 'LRD';
    case LSL = 'LSL';
    case LYD = 'LYD';
    case MAD = 'MAD';
    case MDL = 'MDL';
    case MGA = 'MGA';
    case MKD = 'MKD';
    case MMK = 'MMK';
    case MNT = 'MNT';
    case MOP = 'MOP';
    case MRO = 'MRO';
    case MUR = 'MUR';
    case MVR = 'MVR';
    case MWK = 'MWK';
    case MXN = 'MXN';
    case MXV = 'MXV';
    case MYR = 'MYR';
    case MZN = 'MZN';
    case NAD = 'NAD';
    case NGN = 'NGN';
    case NIO = 'NIO';
    case NOK = 'NOK';
    case NPR = 'NPR';
    case NZD = 'NZD';
    case OMR = 'OMR';
    case PAB = 'PAB';
    case PEN = 'PEN';
    case PGK = 'PGK';
    case PHP = 'PHP';
    case PKR = 'PKR';
    case PLN = 'PLN';
    case PYG = 'PYG';
    case QAR = 'QAR';
    case RON = 'RON';
    case RSD = 'RSD';
    case RUB = 'RUB';
    case RWF = 'RWF';
    case SAR = 'SAR';
    case SBD = 'SBD';
    case SCR = 'SCR';
    case SDG = 'SDG';
    case SEK = 'SEK';
    case SGD = 'SGD';
    case SHP = 'SHP';
    case SLL = 'SLL';
    case SOS = 'SOS';
    case SRD = 'SRD';
    case SSP = 'SSP';
    case STD = 'STD';
    case SVC = 'SVC';
    case SYP = 'SYP';
    case SZL = 'SZL';
    case THB = 'THB';
    case TJS = 'TJS';
    case TMT = 'TMT';
    case TND = 'TND';
    case TOP = 'TOP';
    case TRY = 'TRY';
    case TTD = 'TTD';
    case TWD = 'TWD';
    case TZS = 'TZS';
    case UAH = 'UAH';
    case UGX = 'UGX';
    case USD = 'USD';
    case USN = 'USN';
    case UYI = 'UYI';
    case UYU = 'UYU';
    case UZS = 'UZS';
    case VEF = 'VEF';
    case VND = 'VND';
    case VUV = 'VUV';
    case WST = 'WST';
    case XAF = 'XAF';
    case XCD = 'XCD';
    case XDR = 'XDR';
    case XOF = 'XOF';
    case XPF = 'XPF';
    case XSU = 'XSU';
    case XUA = 'XUA';
    case YER = 'YER';
    case ZAR = 'ZAR';
    case ZMW = 'ZMW';
    case ZWL = 'ZWL';

    public function country(): string
    {
        return match ($this) {
            self::AED => 'Объединенные Арабские Эмираты',
            self::AFN => 'Афганистан',
            self::ALL => 'Албания',
            self::AMD => 'Армения',
            self::ANG => 'Кюрасао, Синт-Мартен',
            self::AOA => 'Ангола',
            self::ARS => 'Аргентина',
            self::AUD => 'Австралия, Кирибати, Кокосовые острова, Науру, Остров Норфолк, Остров Рождества, Остров Херд и острова Макдональд, Тувалу',
            self::AWG => 'Аруба',
            self::AZN => 'Азербайджан',
            self::BAM => 'Босния и Герцеговина',
            self::BBD => 'Барбадос',
            self::BDT => 'Бангладеш',
            self::BGN => 'Болгария',
            self::BHD => 'Бахрейн',
            self::BIF => 'Бурунди',
            self::BMD => 'Бермуды',
            self::BND => 'Бруней',
            self::BOB => 'Боливия',
            self::BOV => 'Боливия',
            self::BRL => 'Бразилия',
            self::BSD => 'Багамские острова',
            self::BTN => 'Бутан',
            self::BWP => 'Ботсванавана',
            self::BYR => 'Беларусь',
            self::BZD => 'Белиз',
            self::CAD => 'Канада',
            self::CDF => 'Конго',
            self::CHE => 'Швейцария',
            self::CHF => 'Лихтенштейн, Швейцария',
            self::CHW => 'Швейцария',
            self::CLF => 'Чили',
            self::CLP => 'Чили',
            self::CNY => 'Китай',
            self::COP => 'Колумбия',
            self::COU => 'Колумбия',
            self::CRC => 'Коста-Рика',
            self::CUC => 'Куба',
            self::CUP => 'Куба',
            self::CVE => 'Кабо-Верде',
            self::CZK => 'Чехия',
            self::DJF => 'Джибути',
            self::DKK => 'Гренландия, Дания, Фарерские острова',
            self::DOP => 'Доминиканская Республика',
            self::DZD => 'Алжир',
            self::EGP => 'Египет',
            self::ERN => 'Эритрея',
            self::ETB => 'Эфиопия',
            self::EUR => 'Австрия, Аландские острова, Андорра, Бельгия, Ватикан, Гваделупа, Гвиана, Германия, Голландия, Греция, Европейский Союх, Ирландия, Испания, Италия, Кипр, Латвия, Литва, Люксембург, Майотта, Мальта, Мартиника, Монако, Португалия, Реуньон, Сан-Марино, Сен-Бартелеми, Сен-Мартин, Сен-Пьер и Микелон, Словакия, Словения, Финляндия, Франция, Французские Южные и Антарктические территории, Черногория, Эстония',
            self::FJD => 'Фиджи',
            self::FKP => 'Мальвинские острова',
            self::GBP => 'Великобритания, Гернси, Джерси, Остров Мен',
            self::GEL => 'Грузия',
            self::GHS => 'Гана',
            self::GIP => 'Гибралтар',
            self::GMD => 'Габмия',
            self::GNF => 'Гвинея',
            self::GTQ => 'Гватемала',
            self::GYD => 'Гайана',
            self::HKD => 'Гонконг',
            self::HNL => 'Гондурас',
            self::HRK => 'Хорватия',
            self::HTG => 'Гаити',
            self::HUF => 'Венгрия',
            self::IDR => 'Индонезия',
            self::ILS => 'Израиль',
            self::INR => 'Бутан, Индия',
            self::IQD => 'Ирак',
            self::IRR => 'Иран',
            self::ISK => 'Исландия',
            self::JMD => 'Ямайка',
            self::JOD => 'Иордания',
            self::JPY => 'Япония',
            self::KES => 'Кения',
            self::KGS => 'Кыргызстан',
            self::KHR => 'Камбоджа',
            self::KMF => 'Коморские острова',
            self::KPW => 'Корея',
            self::KRW => 'Южная Корея',
            self::KWD => 'Кувейт',
            self::KYD => 'Каймановы острова',
            self::KZT => 'Казахстан',
            self::LAK => 'Лаос',
            self::LBP => 'Ливан',
            self::LKR => 'Шри-Ланка',
            self::LRD => 'Либерия',
            self::LSL => 'Лесото',
            self::LYD => 'Ливия',
            self::MAD => 'Западная Сахара, Марокко',
            self::MDL => 'Молдова',
            self::MGA => 'Мадагаскар',
            self::MKD => 'Македония',
            self::MMK => 'Мьянма',
            self::MNT => 'Монголия',
            self::MOP => 'Макао',
            self::MRO => 'Мавритания',
            self::MUR => 'Маврикий',
            self::MVR => 'Мальдивы',
            self::MWK => 'Малави',
            self::MXN => 'Мексика',
            self::MXV => 'Мексика',
            self::MYR => 'Малайзия',
            self::MZN => 'Мозамбик',
            self::NAD => 'Намибия',
            self::NGN => 'Нигерия',
            self::NIO => 'Никарагуа',
            self::NOK => 'Норвегия, Остров Буве',
            self::NPR => 'Непал',
            self::NZD => 'Ниуэ, Новая Зеландия, Острова Кука, Острова Питкэрн, Токелау',
            self::OMR => 'Оман',
            self::PAB => 'Панама',
            self::PEN => 'Перу',
            self::PGK => 'Папуа Новая Гвинея',
            self::PHP => 'Филиппины',
            self::PKR => 'Пакистан',
            self::PLN => 'Польша',
            self::PYG => 'Парагвай',
            self::QAR => 'Катар',
            self::RON => 'Румыния',
            self::RSD => 'Сербия',
            self::RUB => 'Россия',
            self::RWF => 'Руанда',
            self::SAR => 'Саудовская Аравия',
            self::SBD => 'Соломоновы острова',
            self::SCR => 'Сейшельские Острова',
            self::SDG => 'Судан',
            self::SEK => 'Швеция',
            self::SGD => 'Сингапур',
            self::SHP => 'Остров Святой Елены',
            self::SLL => 'Сьерра-Леоне',
            self::SOS => 'Сомали',
            self::SRD => 'Суринам',
            self::SSP => 'Южный Судан',
            self::STD => 'Сан-Томе и Принсипе',
            self::SVC => 'Сальвадор',
            self::SYP => 'Арабская Сирийская Республика',
            self::SZL => 'Свазиленд',
            self::THB => 'Таиланд',
            self::TJS => 'Таджикистан',
            self::TMT => 'Туркменистан',
            self::TND => 'Тунис',
            self::TOP => 'Тонга',
            self::TRY => 'Турция',
            self::TTD => 'Тринидад и Тобаго',
            self::TWD => 'Тайвань',
            self::TZS => 'Танзания',
            self::UAH => 'Украина',
            self::UGX => 'Уганда',
            self::USD => 'Американское Самоа, Бонэйр, Британские Виргинские Острова, Британские территории в Индийском Океане, Виргинские Острова, Гаити, Гуам, Западный Тимор, Маршалловы острова, Микронезия, Острова США, Палау, Панама, Пуэрто-Рико, Сальвадор, Северные Марианские острова, США, Тёркс и Кайкос, Эквадор',
            self::USN => 'США',
            self::UYI => 'Уругвай',
            self::UYU => 'Уругвай',
            self::UZS => 'Узбекистан',
            self::VEF => 'Венесуэла',
            self::VND => 'Вьетнам',
            self::VUV => 'Вануату',
            self::WST => 'Самоа',
            self::XAF => 'Габон, Камерун, Конго, ЦАР, Чад, Экваториальная Гвинея',
            self::XCD => 'Ангилья, Антигуа и Барбуда, Гренада, Доминика, Монтсеррат, Санта-Люсия, Сент-Винсент и Гренадины, Сент-Китс и Невис',
            self::XDR => 'Международный монетарный фонд',
            self::XOF => 'Бенин, Буркина-Фасо, Гвинея-Биссау, Кот-д\'Ивуар, Мали, Нигер, Сенегал, Того',
            self::XPF => 'Новая Каледония, Уоллис и Футуна, Французская Полинезия',
            self::XSU => 'Система "SUCRE"',
            self::XUA => 'Страны Африканского содружества',
            self::YER => 'Йемен',
            self::ZAR => 'Лесото, Намибия, США',
            self::ZMW => 'Замбия',
            self::ZWL => 'Зимбабве',
        };
    }

    public function numericCode(): string
    {
        return match ($this) {
            self::AED => '784',
            self::AFN => '971',
            self::ALL => '008',
            self::AMD => '051',
            self::ANG => '532',
            self::AOA => '973',
            self::ARS => '032',
            self::AUD => '036',
            self::AWG => '533',
            self::AZN => '944',
            self::BAM => '977',
            self::BBD => '052',
            self::BDT => '050',
            self::BGN => '975',
            self::BHD => '048',
            self::BIF => '108',
            self::BMD => '060',
            self::BND => '096',
            self::BOB => '068',
            self::BOV => '984',
            self::BRL => '986',
            self::BSD => '044',
            self::BTN => '064',
            self::BWP => '072',
            self::BYR => '974',
            self::BZD => '084',
            self::CAD => '124',
            self::CDF => '976',
            self::CHE => '947',
            self::CHF => '756',
            self::CHW => '948',
            self::CLF => '990',
            self::CLP => '152',
            self::CNY => '156',
            self::COP => '170',
            self::COU => '970',
            self::CRC => '188',
            self::CUC => '931',
            self::CUP => '192',
            self::CVE => '132',
            self::CZK => '203',
            self::DJF => '262',
            self::DKK => '208',
            self::DOP => '214',
            self::DZD => '012',
            self::EGP => '818',
            self::ERN => '232',
            self::ETB => '230',
            self::EUR => '978',
            self::FJD => '242',
            self::FKP => '238',
            self::GBP => '826',
            self::GEL => '981',
            self::GHS => '936',
            self::GIP => '292',
            self::GMD => '270',
            self::GNF => '324',
            self::GTQ => '320',
            self::GYD => '328',
            self::HKD => '344',
            self::HNL => '340',
            self::HRK => '191',
            self::HTG => '332',
            self::HUF => '348',
            self::IDR => '360',
            self::ILS => '376',
            self::INR => '356',
            self::IQD => '368',
            self::IRR => '364',
            self::ISK => '352',
            self::JMD => '388',
            self::JOD => '400',
            self::JPY => '392',
            self::KES => '404',
            self::KGS => '417',
            self::KHR => '116',
            self::KMF => '174',
            self::KPW => '408',
            self::KRW => '410',
            self::KWD => '414',
            self::KYD => '136',
            self::KZT => '398',
            self::LAK => '418',
            self::LBP => '422',
            self::LKR => '144',
            self::LRD => '430',
            self::LSL => '426',
            self::LYD => '434',
            self::MAD => '504',
            self::MDL => '498',
            self::MGA => '969',
            self::MKD => '807',
            self::MMK => '104',
            self::MNT => '496',
            self::MOP => '446',
            self::MRO => '478',
            self::MUR => '480',
            self::MVR => '462',
            self::MWK => '454',
            self::MXN => '484',
            self::MXV => '979',
            self::MYR => '458',
            self::MZN => '943',
            self::NAD => '516',
            self::NGN => '566',
            self::NIO => '558',
            self::NOK => '578',
            self::NPR => '524',
            self::NZD => '554',
            self::OMR => '512',
            self::PAB => '590',
            self::PEN => '604',
            self::PGK => '598',
            self::PHP => '608',
            self::PKR => '586',
            self::PLN => '985',
            self::PYG => '600',
            self::QAR => '634',
            self::RON => '946',
            self::RSD => '941',
            self::RUB => '643',
            self::RWF => '646',
            self::SAR => '682',
            self::SBD => '090',
            self::SCR => '690',
            self::SDG => '938',
            self::SEK => '752',
            self::SGD => '702',
            self::SHP => '654',
            self::SLL => '694',
            self::SOS => '706',
            self::SRD => '968',
            self::SSP => '728',
            self::STD => '678',
            self::SVC => '222',
            self::SYP => '760',
            self::SZL => '748',
            self::THB => '764',
            self::TJS => '972',
            self::TMT => '934',
            self::TND => '788',
            self::TOP => '776',
            self::TRY => '949',
            self::TTD => '780',
            self::TWD => '901',
            self::TZS => '834',
            self::UAH => '980',
            self::UGX => '800',
            self::USD => '840',
            self::USN => '997',
            self::UYI => '940',
            self::UYU => '858',
            self::UZS => '860',
            self::VEF => '937',
            self::VND => '704',
            self::VUV => '548',
            self::WST => '882',
            self::XAF => '950',
            self::XCD => '951',
            self::XDR => '960',
            self::XOF => '952',
            self::XPF => '953',
            self::XSU => '994',
            self::XUA => '965',
            self::YER => '886',
            self::ZAR => '710',
            self::ZMW => '967',
            self::ZWL => '932',
        };
    }

    public function currencyName(): string
    {
        return match ($this) {
            self::AED => 'Дирхам',
            self::AFN => 'Афгани',
            self::ALL => 'Лек',
            self::AMD => 'Драхм',
            self::ANG => 'Гульден (нидерландский антильский гульден)',
            self::AOA => 'Кванза',
            self::ARS => 'Аргентинский песо',
            self::AUD => 'Австралийский доллар',
            self::AWG => 'Флорин',
            self::AZN => 'Манат',
            self::BAM => 'Конвертируемая марка',
            self::BBD => 'Барбадосский доллар',
            self::BDT => 'Така',
            self::BGN => 'Болгарский лев',
            self::BHD => 'Динар',
            self::BIF => 'Бурундийский Франк',
            self::BMD => 'Бермудский доллар',
            self::BND => 'Брунейский доллар',
            self::BOB => 'Боливиано',
            self::BOV => 'Мвдол',
            self::BRL => 'Бразильский реал',
            self::BSD => 'Доллар',
            self::BTN => 'Нгултрум',
            self::BWP => 'Пула',
            self::BYR => 'Беларусский рубль',
            self::BZD => 'Доллар',
            self::CAD => 'Канадский доллар',
            self::CDF => 'Конголезский франк',
            self::CHE => 'WIR Евро',
            self::CHF => 'Швейцарский франк',
            self::CHW => 'WIR Франк',
            self::CLF => 'Унидад де Фоменто',
            self::CLP => 'Чилийский песо',
            self::CNY => 'Китайский юань',
            self::COP => 'Колумбийский песо',
            self::COU => 'Унидад де валор реаль',
            self::CRC => 'Колон',
            self::CUC => 'Конвертируемый песо',
            self::CUP => 'Песо',
            self::CVE => 'Эскудо',
            self::CZK => 'Чешская крона',
            self::DJF => 'Джибутский Франк',
            self::DKK => 'Датская крона',
            self::DOP => 'Доминиканский песо',
            self::DZD => 'Алжирский динар',
            self::EGP => 'Египетский фунт',
            self::ERN => 'Накфа',
            self::ETB => 'Бирр',
            self::EUR => 'Евро',
            self::FJD => 'Фиджийский доллар',
            self::FKP => 'Фунт',
            self::GBP => 'Фунт Стерлингов',
            self::GEL => 'Лари',
            self::GHS => 'Седи',
            self::GIP => 'Гибралтарский фунт',
            self::GMD => 'Даласи',
            self::GNF => 'Гвинейский франк',
            self::GTQ => 'Кетсаль',
            self::GYD => 'Гайнаский доллар',
            self::HKD => 'Гонконгский доллар',
            self::HNL => 'Лемпира',
            self::HRK => 'Куна',
            self::HTG => 'Гурд',
            self::HUF => 'Форинт',
            self::IDR => 'Рупия',
            self::ILS => 'Новый израильский шекель',
            self::INR => 'Индийская рупия',
            self::IQD => 'Иракский динар',
            self::IRR => 'Иранский риал',
            self::ISK => 'Исландская крона',
            self::JMD => 'Доллар',
            self::JOD => 'Иорданский динар',
            self::JPY => 'Йена',
            self::KES => 'Кенийский шиллинг',
            self::KGS => 'Сом',
            self::KHR => 'Риель',
            self::KMF => 'Коморский франк',
            self::KPW => 'Северо-корейский вон',
            self::KRW => 'Вон',
            self::KWD => 'Кувейтский динар',
            self::KYD => 'Доллар',
            self::KZT => 'Тенге',
            self::LAK => 'Кип',
            self::LBP => 'Ливанский фунт',
            self::LKR => 'Рупия',
            self::LRD => 'Либерийский доллар',
            self::LSL => 'Лоти',
            self::LYD => 'Ливийский динар',
            self::MAD => 'Марокканский дирхам',
            self::MDL => 'Лей',
            self::MGA => 'Малагасийский ариари',
            self::MKD => 'Денар',
            self::MMK => 'Кьят',
            self::MNT => 'Тугрик',
            self::MOP => 'Патака',
            self::MRO => 'Угия',
            self::MUR => 'Маврикийская рупия',
            self::MVR => 'Руфия',
            self::MWK => 'Квача',
            self::MXN => 'Мексиканский песо',
            self::MXV => 'Мексиканский UDI',
            self::MYR => 'Малайзийский рингит',
            self::MZN => 'Мозамбикский метикал',
            self::NAD => 'Намибийский доллар',
            self::NGN => 'Наира',
            self::NIO => 'Кордоба',
            self::NOK => 'Норвежская крона',
            self::NPR => 'Непальская рупия',
            self::NZD => 'Новозеландский доллар',
            self::OMR => 'Оманский риал',
            self::PAB => 'Бальбоа',
            self::PEN => 'Новый соль',
            self::PGK => 'Кина',
            self::PHP => 'Филиппинский песо',
            self::PKR => 'Пакистанская рупия',
            self::PLN => 'Слотый',
            self::PYG => 'Гуарани',
            self::QAR => 'Катарский риал',
            self::RON => 'Лей',
            self::RSD => 'Сербиский динар',
            self::RUB => 'Российский рубль',
            self::RWF => 'Франк',
            self::SAR => 'Риял',
            self::SBD => 'Соломонский доллар',
            self::SCR => 'Рупия',
            self::SDG => 'Суданский фунт',
            self::SEK => 'Шведская крона',
            self::SGD => 'Сингапурский доллар',
            self::SHP => 'Фунт Святой Елены',
            self::SLL => 'Леоне',
            self::SOS => 'Сомалийский шиллинг',
            self::SRD => 'Суринамский доллар',
            self::SSP => 'Южно-суданский фунт',
            self::STD => 'Добра',
            self::SVC => 'Сальвадорский колон',
            self::SYP => 'Сирийский фунт',
            self::SZL => 'Лилангени',
            self::THB => 'Бат',
            self::TJS => 'Сомони',
            self::TMT => 'Новый туркменский манат',
            self::TND => 'Тунисский динар',
            self::TOP => 'Паанга',
            self::TRY => 'Турецкая лира',
            self::TTD => 'Доллар',
            self::TWD => 'Новый тайваньский доллар',
            self::TZS => 'Танзанийский шиллинг',
            self::UAH => 'Гривна',
            self::UGX => 'Угандийский шиллинг',
            self::USD => 'Доллар США',
            self::USN => 'Доллар США (на след. день)',
            self::UYI => 'Песо (URUIURUI)',
            self::UYU => 'Песо',
            self::UZS => 'Узбекский сум',
            self::VEF => 'Боливар',
            self::VND => 'Донг',
            self::VUV => 'Вату',
            self::WST => 'Тала',
            self::XAF => 'Франк (франк КФА BEAC)',
            self::XCD => 'Восточно-карибский доллар',
            self::XDR => 'Специальные права заимствования',
            self::XOF => 'Франк (франк КФА BCEAO)',
            self::XPF => 'CFP Франк',
            self::XSU => 'Сукре',
            self::XUA => 'Условная единица ADB',
            self::YER => 'Риал',
            self::ZAR => 'Ранд',
            self::ZMW => 'Замбийская квача',
            self::ZWL => 'Зимбабвийский доллар',
        };
    }

    public function toCurrencyCode(): CurrencyCode
    {
        return new CurrencyCode($this->value);
    }
}
